context:
  name: geoh5-interop
  version: "1.4.1.post1"
  python_min: '3.10'
  module_name: ${{ name|lower|replace("-", "_") }}


package:
  name: ${{ name|lower|replace('_', '-') }}
  version: ${{ version }}

source:
  url: https://github.com/MiraGeoscience/${{ name }}/archive/v${{ version }}.tar.gz
  sha256: 9734076090fcaae8710a49c1713ead713da253881fafbb6c9e73b0f074306b3f

build:
  number: 0
  noarch: python
  script:
    - export POETRY_DYNAMIC_VERSIONING_BYPASS=${{ version }}
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - poetry-core >=1.8.0
    - poetry-dynamic-versioning >=1.9, 1.*
    - setuptools
  run:
    - python >=${{ python_min }}
    - geoh5py >=0.12.1, 0.12.*
    - las-geoh5 >=0.3.2, 0.3.*
    - mira-omf >=3.3.2, 3.3.*

tests:
  - python:
      python_version: ${{ python_min }}.*
      imports:
        - ${{ module_name }}
        - ${{ module_name }}._version
        - geoh5py
        - las_geoh5
        - omf
        - properties
      pip_check: false  # something wrong with properties 0.6.1, but installation seems correct nonetheless
  - script:
      - pip list
    requirements:
      run:
        - pip
  - package_contents:
      files:
        - site-packages/${{ module_name }}/_version.py

about:
  homepage: https://www.mirageoscience.com/mining-industry-software/python-integration
  summary: 'A meta-package that groups together packages for interoperability between GEOH5 and other file formats.'
  repository: https://github.com/MiraGeoscience/geoh5-interop

  description: |
    This meta-package collects the following packages:
    - [geoh5py](https://github.com/MiraGeoscience/geoh5py)
    - [mira-omf](https://github.com/MiraGeoscience/omf)
    - [las-geoh5](https://github.com/MiraGeoscience/las-geoh5)

    See the individual package documentation for more information.

  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/geoh5py
